### ISSUE TITLE
Unable to run PiG with --tempBuild specified

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#326] opened 2020-08-20 18:55 UTC
```
$ bacon pig run --tempBuild /workDir/workspace/pnc-2.0/test-java/cpaas-test-java/cpaas-test-pig-project/config/cpaas/development
[INFO ] - Generating milestone for versionId ProductVersion(super=ProductVersionRef(id=234, version=1.0, attributes={BREW_TAG_PREFIX=cpaas-tp-1.7-pnc}), product=ProductRef(id=175, name=CPaaS Test Product, description=null, abbreviation=cpaas-tp, productManagers=null, productPagesCode=null), currentProductMilestone=ProductMilestoneRef(id=257, version=1.0.0.ER1, endDate=null, startingDate=2020-08-06T00:00:00Z, plannedEndDate=2020-08-07T00:00:00Z), productMilestones={257=ProductMilestoneRef(id=257, version=1.0.0.ER1, endDate=null, startingDate=2020-08-06T00:00:00Z, plannedEndDate=2020-08-07T00:00:00Z), 269=ProductMilestoneRef(id=269, version=1.0.1.DR1, endDate=null, startingDate=2020-08-12T00:00:00Z, plannedEndDate=2020-08-13T00:00:00Z)}, productReleases={}, groupConfigs={646=GroupConfigurationRef(id=646, name=CPAAS-TP-1.0)}, buildConfigs={2338=BuildConfigurationRef(id=2338, name=dcheung-test-cpaas.tp-cpaas-test-pnc-gradle-1.0.0, description=null, buildScript=gradle clean publish, scmRevision=master, creationTime=2020-08-12T19:44:50.882Z, modificationTime=2020-08-12T19:44:50.866Z, buildType=GRADLE, defaultAlignmentParams=--info -DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DignoreUnresolvableDependencies=true), 2315=BuildConfigurationRef(id=2315, name=cpaas.tp-cpaas-test-pnc-gradle-1.0.0, description=null, buildScript=gradle clean publish, scmRevision=master, creationTime=2020-08-06T08:54:20.323Z, modificationTime=2020-08-19T16:24:21.383Z, buildType=GRADLE, defaultAlignmentParams=--info -DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DignoreUnresolvableDependencies=true), 2336=BuildConfigurationRef(id=2336, name=cpaas.tp-cpaas-test-pnc-maven-1.x, description=null, buildScript=mvn -Dinsecure.repositories=WARN clean deploy, scmRevision=master, creationTime=2020-08-12T12:13:14.946Z, modificationTime=2020-08-12T12:13:25.174Z, buildType=MVN, defaultAlignmentParams=-DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DversionSuffixStrip= -DreportNonAligned=true)}) and milestone 1.0.0.ER1 in PNC
[INFO ] - Adding/updating build configurations
[INFO ] - Temporary build
[INFO ] - Temporary build
[INFO ] - Performing builds of build group 646 in PNC
[INFO ] - waiting for finish of group build 2029
[INFO ] - group build finished successfully
[ERROR] - Something wrong happened: 
org.jboss.pnc.bacon.pig.impl.pnc.NoSuccessfulBuildException: Unable to find a successful build of build config '2315'
	at org.jboss.pnc.bacon.pig.impl.pnc.BuildInfoCollector.getLatestBuild(BuildInfoCollector.java:87)
	at org.jboss.pnc.bacon.pig.PigFacade.lambdazsh(PigFacade.java:356)
	at java.util.stream.ReferencePipeline.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline.accept(ReferencePipeline.java:193)
	at java.util.ArrayList.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ReduceOps.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.jboss.pnc.bacon.pig.PigFacade.getBuilds(PigFacade.java:357)
	at org.jboss.pnc.bacon.pig.PigFacade.build(PigFacade.java:101)
	at org.jboss.pnc.bacon.pig.PigFacade.run(PigFacade.java:138)
	at org.jboss.pnc.bacon.pig.Pig.doExecute(Pig.java:244)
	at org.jboss.pnc.bacon.pig.Pig.doExecute(Pig.java:134)
	at org.jboss.pnc.bacon.pig.Pig.lambdazsh(Pig.java:126)
	at org.jboss.pnc.bacon.common.cli.AbstractCommand.executeHelper(AbstractCommand.java:205)
	at org.jboss.pnc.bacon.pig.Pig.execute(Pig.java:115)
	at org.aesh.command.impl.operator.EndOperator.execute(EndOperator.java:41)
	at org.aesh.command.impl.Executions.execute(Executions.java:213)
	at org.aesh.command.impl.AeshCommandRuntime.executeCommand(AeshCommandRuntime.java:161)
	at org.jboss.pnc.bacon.cli.App.run(App.java:97)
	at org.jboss.pnc.bacon.cli.App.main(App.java:128)
```

**Comment by goldmann** [comment] 2020-08-20 18:55
@rnc FYI

**Comment by thescouser89** [comment] 2020-08-24 19:21
Closing since Jan  created this PR. This means that you may get permanent builds in your result with the --tempBuilds flag, but apparently it's by design.

**Closed by thescouser89** 2020-08-24 19:21 UTC
